# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='label',
            new_name='labels',
        ),
    ]
