# Generated by Django 2.0 on 2017-12-12 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_auto_20171202_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookmarks', to='bookmark.Label'),
        ),
    ]
