# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='finished',
            field=models.DateTimeField(default=None),
        ),
    ]
