# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20171124_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='finished',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
